[package]
name = "actix_test"
version = "0.1.0"
authors = ["Zedjones <dojoman19@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "2.0"
actix-rt = "1.1.0"
serde = "1.0.106"
env_logger = "0.7.1"
lapin = "0.39.1"
cfg-if = "0.1.10"