[package]
name = "gaia_web"
version = "0.1.0"
authors = ["Zedjones <dojoman19@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "2.0"
actix-rt = "1.1.0"
actix-multipart = "0.2.0"
serde = "1.0.106"
log = "0.4.8"
env_logger = "0.7.1"
lapin = "0.39.7"
futures = "0.3.4"
diesel = "1.4.4"
diesel_migrations = "1.4.0"