version: "3.5"
services:
    rabbitmq:
        image: "rabbitmq:3-management"
        ports: 
            - 15672:15672
            - 5672:5672
    gaia:
        build:
            context: ..
            dockerfile: docker/Dockerfile
        environment: 
            RABBITMQ_ADDR: rabbitmq
        ports: 
            - 8080:8000
    worker:
        build:
            context: ../worker
            dockerfile:  ../worker/Dockerfile
        environment:
            RABBITMQ_ADDR: rabbitmq